### ISSUE TITLE
Daily Log Inbox

### ISSUE THREAD

**Issue by ntrappe** [ntrappe/cse112-s22-group2#14]
## Daily Log Inbox
(HTML Page + JS)

### `daily-log-inbox.html`
<img width="438" alt="Screen Shot 2022-05-13 at 7 26 50 PM" src="https://user-images.githubusercontent.com/33298966/168407476-db32ab41-9cd5-4d8e-8cfa-12bf5e06d0ba.png">

**Expectations:**
Daily log inbox displays the daily log previews (if available) + offers CRUD interactions. The CRUD interactions do not have to tie into back-end right now but some should trigger warnings/messages.

**Features:**
- [x] in header, title of page should be "Daily Logs"
- [x] right side of header has **Edit**button
- [x] when **Edit** button pressed, user should be able to select logs or at least have the select icon visible (see below)
- [x] when **Edit** button pressed, toggles to **Cancel** and if pressed, returns to normal state (and normal toolbar)
- [x] toolbar at bottom should have 2 modes: normal OR edit
  - [x] normal: says the number of logs "9 Logs" + have a new button/icon
  - [x] edit: has 2 buttons: delete all AND delete
- [x] if user clicks **Delete All** then pop up message to confirm
- [x] if user selects some logs + **Delete** then pop up message to confirm
- [ ] if user doesn't select +  **Delete** then nothing? or message

---

When **`Edit`** clicked:
<img width="461" alt="Screen Shot 2022-05-13 at 7 27 16 PM" src="https://user-images.githubusercontent.com/33298966/168407487-ff896553-8c1f-4f65-bf69-2ee1bec87f02.png">
Error message example:
<img width="316" alt="Screen Shot 2022-05-13 at 7 27 50 PM" src="https://user-images.githubusercontent.com/33298966/168407506-0e831e7e-b613-4163-b355-f58fd73aab10.png">

**Comment by Alex-942** [comment]
For now the functionality will be just to do nothing when the user clicks delete selected but did not select any logs
